site: szlent's blog
url: undersilence.github.io
title: Sidey
description: Simple and minimalistic jekyll blogging theme.
author:
  name: szlent
  email: undersilence@qq.com
  url: undersilence.github.io
permalink: pretty

baseurl: "undersilence.github.io"

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false

exclude:
  - .jekyll-cache

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

gittalk:
  clientID: 6ef58bbbe28ef2cf95c1 # GitHub Application Client ID
  clientSecret: 32b87abd104f15768e1db0691386ccc8402c9ea8  # GitHub Application Client Secret,
  repository: undersilence.github.io  # Storage gittalk's repository
  owner: undersilence  # GitHub repo owner,
  admin: undersilence  # GitHub repo owner and collaborators, only these guys can initialize github issues eg. 'colynn,daattali'